service: sls-cfn-diagram
#app: your-app-name

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  region: us-west-1
  stage: dev
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}

custom:
  prune:
    automatic: true
    number: 2
  webpack:
    config: ./webpack.config.js
  postsTableName: post-table-${self:provider.stage}

functions:
  createPost:
    handler: src/handlers/createPost.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: post
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt PostsTable.Arn

plugins:
  # - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-webpack

package:
  individually: true

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
