name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  cfnDigram:
    name: cfnDiagram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serverless/github-action@v3.1
        # - uses: actions/setup-node@v3
        with:
          args: package
      - run: |
          npm install -g @mhlabs/cfn-diagram
          npm install -g draw.io-export
          cfn-dia draw.io -t .serverless/cloudformation-template-update-stack.json -c -o diagram.drawio
          uniqueBucketName="cloudgto-diagram"-"$(uuidgen | tr "[:upper:]" "[:lower:]")"
          ls -a
          echo $uniqueBucketName
          aws s3 mb s3://$uniqueBucketName
          aws s3 cp diagram.png s3://$uniqueBucketName

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
